# Generated by Django 3.2.5 on 2021-07-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='name',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
