# Generated by Django 3.2.5 on 2021-07-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0005_alter_data_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srfid', models.IntegerField(unique=True)),
                ('bcode', models.TextField(unique=True)),
                ('pname', models.TextField()),
                ('mobno', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.TextField()),
                ('address', models.TextField()),
                ('ccode', models.TextField()),
                ('dname', models.TextField()),
                ('rem', models.TextField()),
                ('cexe', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('loc', models.TextField()),
                ('runid', models.TextField()),
                ('runtime', models.IntegerField()),
                ('icmrup', models.TextField()),
                ('accid', models.IntegerField(unique=True)),
                ('res', models.TextField()),
                ('ctval', models.IntegerField()),
            ],
        ),
    ]
