# Generated by Django 3.2.5 on 2021-07-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0007_alter_pdata_srfid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdata',
            name='accid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pdata',
            name='bcode',
            field=models.TextField(),
        ),
    ]
