# Generated by Django 3.2.5 on 2021-07-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0009_pdata_runstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdata',
            name='accid',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pdata',
            name='age',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pdata',
            name='ctval',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pdata',
            name='mobno',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pdata',
            name='runtime',
            field=models.TextField(),
        ),
    ]
