# Generated by Django 3.2.5 on 2021-08-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0010_auto_20210729_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='regdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srfid', models.BigIntegerField(unique=True)),
                ('pname', models.TextField()),
                ('mobno', models.TextField()),
                ('Age', models.TextField()),
                ('Gender', models.TextField()),
                ('Address', models.TextField()),
                ('ccode', models.TextField()),
                ('dname', models.TextField()),
                ('rem', models.TextField()),
                ('cexe', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
    ]
