# Generated by Django 3.2.5 on 2021-08-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0012_auto_20210802_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdata',
            name='srfid',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='regdata',
            name='srfid',
            field=models.TextField(unique=True),
        ),
    ]
